UI tests
andrei-vlah/teamcity-testing-framework pull request #6
Opened 2024-11-09 19:22 UTC by andrei-vlah

2024-11-10 20:50 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-10 20:50 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateProjectTest.java
> +        System.out.println();
Наверное, осталось от дебага?

2024-11-10 20:50 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/CreateProjectTest.java
> +        buildTypePage.createBuildType(GITHUB_SPRING_CORE.getRepo(), EMPTY_STRING);
Отлично! Только не хватает проверки на API уровне, что сущность не была создана.

2024-11-11 09:52 UTC, andrei-vlah commented on src/test/java/com/example/teamcity/ui/CreateProjectTest.java
> +        System.out.println();
Да, забыл убрать, спасибо

2024-11-11 09:52 UTC, andrei-vlah commented on src/test/java/com/example/teamcity/ui/CreateProjectTest.java
> +        buildTypePage.createBuildType(GITHUB_SPRING_CORE.getRepo(), EMPTY_STRING);
ок, доделаю, спасибо :)

2024-11-24 22:31 UTC, merged